### ISSUE TITLE
robustesse

### ISSUE THREAD

**Issue by byache** [cspaier/pronote2wims#1]
https://github.com/cspaier/pronote2wims/blob/3adb0dc07a2b91502da76acc7c6503b77b6deed0/pronote2wims.py#L51

si on veut que le truc marche même lorsqu'il n'y a pas d'entête, il faut essentiellement changer cette ligne. Tu pourrais me l'expliquer ? 
Dans mon fichier, je prenais les caractères un par un et tant qu'ils étaient en majuscules, c'était le nom, puis après, tant qu'il n'y avait pas de virgule, c'était le prénom :-)
Je ne sais pas si il y aurait un autre moyen? Ou alors : la premiere colonne est forcément celle du "NOMespaceprénom" (avec des espaces possibles dans les nom et prénom...)

**Comment by cspaier** [comment]
Je ne suis pas certain qu’il faille changer cette ligne.

`' '.join(re.findall(r"\b[A-Z][A-Z]+\b", ligne["Élève"]))`  va te renvoyer les mots en majuscules dans la chaîne de caractère `ligne["Élève"]`.
En détail, et exemple:
Admettons que `ligne["Élève"]` vaille `"NOM COMPOSE Prenom Compose"`.
`re.findall(r"\b[A-Z][A-Z]+\b", ligne["Élève"])` var renvoyer tous les mots en majuscules dans`ligne["Élève"]`. Dans l'exemple `["NOM", "COMPOSE"]`
`'  '.join()` va concaténer les éléments de cette liste en ajoutant un espace ` `  entre chaque élément.

C'est une manière rapide de choper le nom d'un élève.
Notons qu'a la ligne suivante, on chope le prénom avec: 
https://github.com/cspaier/pronote2wims/blob/3adb0dc07a2b91502da76acc7c6503b77b6deed0/pronote2wims.py#L53

En fait, ce qu'il faudra changer c'est cette ligne je pense:
https://github.com/cspaier/pronote2wims/blob/3adb0dc07a2b91502da76acc7c6503b77b6deed0/pronote2wims.py#L123
Ca construit un une liste de dictionaire ou les noms des clefs sont basées sur l'entête.

L'exemple que tu m'as donné par email est formaté comme cela:
```
NOM COMPOSE Prenom
NOM Prenom
Moy. de la classe :
```
Comment tu l'as construit?
Je suis pas certain que ce soit du csv franchement: Pas d'entête ni séparateur de champ. Disons que c'est un csv sans entête avec un seul champ par ligne. Du coup c'est un fichier texte.

Pour analyser ce fichier on a deux possibilités:
1. Ne pas modifier la fonction `csv2list`:
 On lit les données lignes par ligne on fait un truc du genre:
```
csv_list = []
for ligne in lignes:
    csv_list.append({"Élève": ligne})
```
2. modifier `csv2list`

Dans tous les cas, il faut pouvoir déterminer le format du fichier en amont.

**Comment by cspaier** [comment]
Hum, c’est pas résolu si?

**Comment by cspaier** [comment]
Je viens de tester et non. Je réouvre.

**Comment by cspaier** [comment]
Je pense qu'on est bon: 

- On accepte n'importe quel csv dont le premier champ est  `NOM Prénom`
- On ne lit pas les lignes qui ne contiennent pas de mot en majuscules (malin ton astuce!)

Faudrait tester avec plein d'export pronotes. Je pense aussi mettre un lien plus visible vers le github pour inviter les gens à créer des issues si besoin.
