### ISSUE TITLE
l ou I

### ISSUE THREAD

**Issue by al-coloic** [cspaier/pronote2wims#12]
Salut,

est-il possible d'exclure de la création des mdp, les i majuscules, les L minuscules et les o majuscules.

Galère avec les élèves...
bisous

**Comment by cspaier** [comment]
Bien vu!

Pour les motivés c'est par ici: 
https://github.com/cspaier/pronote2wims/blob/091265a2ce5e2fcfb481bce57391af3306bde7b6/utils.py#L4-L7

Un petit `lettersAndDigits = lettersAndDigits.replace('l', '').replace('I', '').replace('O', '')` devrait faire l'affaire.
