### ISSUE TITLE
majuscules dans les mots de passe

### ISSUE THREAD

**Issue by byache** [cspaier/pronote2wims#14]
https://github.com/cspaier/pronote2wims/blob/f70d4d6bfd45479de0eb6fcaf0a18ba8773a5ce5/pronote2wims.py#L19

J'ai inscrit une classe pour l'instant avec pronote2wims et j'ai eu la surprise de voir que le login des élèves était de la forme
Cesarj (pour Jules César).
Bref, je trouve que ce serait mieux d'ajouter la mise systématique en casse minuscule dans la fonction nettoyer() ...

**Comment by byache** [comment]
Bon, je viens de réutiliser p2w et je n'ai plus rencontré ce problème. Il a du être corrigé entre ma première classe et aujourd'hui... Désolé, je n'avais pas suivi.

**Comment by cspaier** [comment]
Pas de souci.
Pour référence, on met en minuscule dans `id_factory` et ca n'a pas bougé depuis avril dernier:

https://github.com/cspaier/pronote2wims/blob/f70d4d6bfd45479de0eb6fcaf0a18ba8773a5ce5/pronote2wims.py#L28-L54

Ca me fait me demander si on devrait mettre tout ces `lower()` dans `nettoyer()` mais bon c'est du style.

**Comment by byache** [comment]
Autant pour moi, ce n'était pas dans l'ID, mais dans le password qu'il subsiste des majuscules...
(Je me suis à nouveau fait avoir un créant encore une classe :-)
Du coup, si je rajoute un `.lower()` dans mdp_factory, ça ne choque personne ?

**Comment by cspaier** [comment]
J'ai ajouté `.lower()` dans `nettoyer()`.
Du coup j'ai enlevé des `.lower()` à droite et à gauche dans `id_factory` et `mdp_factory`.
Notons que les champs `lastname` et `firstname` ne font pas appel à `nettoyer()`.
https://github.com/cspaier/pronote2wims/blob/d27167afbe2b15c5abf066991ef50018e2521402/pronote2wims.py#L86-L87

Je ne pense pas que tu faisais référence aux mots de passe aléatoires @byache ?

**Comment by byache** [comment]
C'est nickel. Je parlais seulement des MDP 'prenom'
