### ISSUE TITLE
nouveau délimiteur de csv

### ISSUE THREAD

**Issue by cspaier** [cspaier/pronote2wims#15]
En utilisant le client pronote 2021 0.2.1 (32 bit) sous wine j'obtiens des csv ayant pour délimiteur la tabulation `\t`.

J'ai tenté d'utiliser [csv.Sniffer](https://docs.python.org/3/library/csv.html#csv.Sniffer) mais  j'obtiens `csv.Error: Could not determine delimiter`.
Je vais tester la présence du caractère `;` en espérant que pronote ne mette jamais ce caractère dans un champ.

**Comment by byache** [comment]
Salut Clement !
Alors le client 2021 ne s'installe pas facilement sous linux (pour ce que j'ai vu) donc je ne l'ai pas encore essayé :-)
Ce n'est pas possible de tester la présence d'une tabulation ?

**Comment by byache** [comment]
Ah, OK. Je viens de voir le code. Ma remarque est inutile. On verra bien mais ça devrait fonctionner....
