### ISSUE TITLE
Problème majuscule accentuées et login identiques

### ISSUE THREAD

**Issue by elleagn** [cspaier/pronote2wims#16]
Bonjour,
J'ai rencontré 2 problèmes avec la liste de mes élèves.
Cela ne fonctionne pas si un élève a une majuscule accentuée en début de son prénom. Je pense qu'il faudrait utiliser [\p{Lu}] pour avoir toutes les majuscules au lieu de [A-Z].
Ensuite, si deux élèves ont le même nom de famille et la même première lettre de prénom cela plante aussi. _ll faudrait peut être utiliser Counter du module collections pour rajouter un nombre à la fin du login s'il y en a plusieurs élèves avec le même ?

**Comment by byache** [comment]
Merci pour le retour. Il y a deux choses : 
- pour les erreurs avec les caractères accentués, effectivement on peut facilement automatiser une correction, mais en même temps, là, le problème est signalé en rouge et l'utilisateur peut faire la correction facilement. C'est peut-être mieux de laisser comme c'est car un point de vigilance est signalé ?
- pour les doublons, justement il n'y a aucun signalement par pronote2wims et on devrait peut-être mettre les doublons en rouge avec un petit message ? (Car sinon, wims ne fera pas l'inscription correctement...)

**Comment by cspaier** [comment]
Bonjour,
En effet, merci @elleagn pour le retour.

1.  J'ai reproduit en utilisant le fichier csv de test et en changeant "ALADIN Marthe" par "ÀLADIN Marthe". Cette pauvre Marthe n'apparait pas du tout dans le tableau. Il faut modifier cette partie https://github.com/cspaier/pronote2wims/blob/aac8388f59eb248c67ff840290b6701dde848384/pronote2wims.py#L105-L111
2. Effectivement, ce cas n'est pas géré. Je ne connais pas Counter mais ça à l'air pertinent.

Techniquement, il y a deux bugs. Je vais ouvrir deux issues et fermer celle la.
Je ne vais pas avoir le temps de bosser dessus pour l'instant. PR welcome!

**Comment by cspaier** [comment]
J'ai mis à jour le fichier `csvtest` pour faciliter les tests.
Je ferme et on travail dans #17 et #18.
