### ISSUE TITLE
template

### ISSUE THREAD

**Issue by byache** [cspaier/pronote2wims#2]
dans le template, j'ai ajouté une option "p+nom" (j'ai mis un '+' au lieu du point car je trouve qu'on comprend mieux, mais bon...)

par contre, cette option n'apparait pas sur heroku : je ne comprend pas pourquoi.

je ne trouve pas comment mettre un truc par défaut dans le champ de mot de passe fixe

il restera à faire attention : les login et les password doivent avoir au moins 4 caractères

**Comment by byache** [comment]
premiers points réglés.

il restera à faire attention : les login et les password doivent avoir au moins 4 caractères

**Comment by cspaier** [comment]
> il restera à faire attention : les login et les password doivent avoir au moins 4 caractères

Chez wims tu veux dire?

Si oui, il faut qu'on teste de notre coté.

**Comment by byache** [comment]
fait
