### ISSUE TITLE
mdp date de naissance

### ISSUE THREAD

**Issue by byache** [cspaier/pronote2wims#3]
là en testant, les mot de passe date de naissance ne marchent pas.
Mais de toute façon, il vaut mieux enlever cette possibilité ?
Du coup je ne débugue pas...

**Comment by cspaier** [comment]
Après avoir débugué, j’ai créé une branche [birthday](https://github.com/cspaier/pronote2wims/tree/birthday) en ajoutant un avertissement rgpd dans le readme. C'est là au cas où.

J’ai ensuite enlevé du html, js et python.
