### ISSUE TITLE
exemple gbrassens

### ISSUE THREAD

**Issue by byache** [cspaier/pronote2wims#4]
il y a un truc qui déconne dans le template au niveau de l'exemple avec georges brassens, mais je n'ai pas bien compris...

**Comment by cspaier** [comment]
Tu as mis le même `id` pour les deux exemples:
https://github.com/cspaier/pronote2wims/blob/b5221fefe226cd46e9372e51322b41de9ee32ff5/templates/pronote2wims.html#L39-L41

Il faudra changer cette fonction qui affiche/cache les exemples en fonction de l'état du `select`:
https://github.com/cspaier/pronote2wims/blob/b5221fefe226cd46e9372e51322b41de9ee32ff5/templates/pronote2wims.html#L87-L105

**Comment by byache** [comment]
OK. Corrigé.
Je n'avais pas vu la fonction changeSelectId...
