### ISSUE TITLE
desaccentuer

### ISSUE THREAD

**Issue by byache** [cspaier/pronote2wims#5]
actuellement, s'il y a un accent dans le nom de famille, la lettre disparait (je crois).
Ca ne se voit pas trop car les majuscules accentuées sont rares, mais ce n'est pas bien.

Si on met le prénom en mot de passe, là sa se voit plus : les accents ne disparaissent pas.

Il faudrait coder un truc qui désaccentue tout au début des factoires id et mdp...

**Comment by byache** [comment]
C'est fait. J'ai ajouté la fonction desaccent(mot) de mon fichier python initial (en y ajoutant tant qu'on y est les majuscules accentuées).
Je pense que cette fonction n'est pas optimale car elle fait plein de "replace" et de recherche d'accents pour rien, mais elle marche :-)

**Comment by cspaier** [comment]
Il y a plus simple et robuste: [Unidecode](https://pypi.org/project/Unidecode/).
Voir exemple d'utilisation [ici](https://stackoverflow.com/questions/517923/what-is-the-best-way-to-remove-accents-in-a-python-unicode-string).

**Comment by cspaier** [comment]
Tu veux désaccentuer et enlever les caractères spéciaux uniquement au niveau du mot de passe et id wims ou aussi dans les champs prénom et nom?

**Comment by byache** [comment]
Parfait !
