### ISSUE TITLE
Documenter

### ISSUE THREAD

**Issue by cspaier** [cspaier/pronote2wims#6]
J'ai fait une template nommée [help](https://github.com/cspaier/pronote2wims/blob/master/templates/help.html).

Il faudrait expliquer comment exporter de pronote, comment utiliser notre outil et, enfin, comment importer dans wims.

**Comment by byache** [comment]
c'est fait. J'ai aussi fait un tuto pour les collègues de diderot. Il est dans static > media, mais comme c'est très moche, je ne me suis pas résolu à faire un lien dessus...

**Comment by cspaier** [comment]
Nickel. Merci!

J'ai vu que tu avais aussi complété l'aide en ligne. Au top!

Je serais pour peaufiner l'aide en ligne et ajouter un bouton pour l'exporter en pdf. Doit bien y avoir un moyen de faire ca proprement.

L'avantage c'est que comme ca, on aura un seul endroit à mettre à jour ou modifier à l'avenir.

On ferme!
