### ISSUE TITLE
mdp prénoms trop courts

### ISSUE THREAD

**Issue by Badatos** [cspaier/pronote2wims#8]
Bonjour,
Quand on choisi le mot de passe de type "prénom", on court le risque que le fichier csv ne soit pas accepté par WIMS à cause de mot de passe trop court (<4), ce qui peut être assez fréquent en fait (Léa, Noé, Luc, Eva, ....)
Pouvez-vous mettre en place une alerte quand un prénom trop court est détecté dans le fichier Pronote ? (voir empêcher le choix de ce type de mot de passe dans ce cas)

**Comment by cspaier** [comment]
Bonjour,
Merci de votre intérêt pour ce projet.

On a deja des tests de longueurs sur les champs `mot de passe` et `identifiant`:

https://github.com/cspaier/pronote2wims/blob/a107d1b13c1349662bf5576a822ba081d4726096/pronote2wims.py#L47-L51

https://github.com/cspaier/pronote2wims/blob/a107d1b13c1349662bf5576a822ba081d4726096/pronote2wims.py#L67-L70

En principe les erreurs se retrouvent de le tableau de prévisualisation en rouge.

Si vous constatez un bug, merci de fournir un CSV permettant de reproduire.

> voir empêcher le choix de ce type de mot de passe dans ce cas

Le choix qui a été fait pour l'instant est d'autoriser les erreurs mais de les indiquer dans le tableau de prévisualisation. Ce tableau est éditable donc l'utilisateur peut au choix corriger au cas par cas ou changer l'option.

Notons que les tests d'erreurs sont effectués en python côté serveur pour l'instant (voir [cette issue](https://github.com/cspaier/pronote2wims/issues/7#issuecomment-610380694)).

**Comment by Badatos** [comment]
Je n'ai pas accès à Pronote, je n'ai donc pas pu tester moi même. Je vous rapporte un souci signalé par une enseignante via le forum WIMSEDU ici : https://wimsedu.info/?topic=inscription-des-eleves-via-liaison-tableur-et-pronote#post-5923

**Comment by cspaier** [comment]
Merci d'avoir transmis le problème.

A vue de nez deux choses sont possibles:

- L'utilisatrice n'a pas vu les erreurs.
- Les erreurs n'ont pas été affichée dans le tableau de prévisualisation.

Je vous contacte pour m'inscrire sur wimsedu afin de pouvoir suivre ces problèmes directement.

**Comment by Badatos** [comment]
Oui je suis d'accord avec votre analyse. Je ne connaissais pas ce tableau de prévisualisation, mais en effet soit elle ne l'a pas vu, soit elles n'ont pas été affichées.
À bientôt sur WIMS EDU ;)

**Comment by cspaier** [comment]
Je viens de tester avec les CSV suivant:
```
﻿Élève;;Né(e) le;Sexe;Entrée;Sortie;Classe de rattachement;Option 1;Option 2;Option 3;Autres options
"ALADIN Marthe";"";"19/01/2005";"F";01/09/2020;;"";"ANGLAIS LV1";"ESPAGNOL LV2";"ACCOMPAGNEMT. PERSO.";"ACCOMP.CHOIX ORIENT."
"ALLUMINIUM Paul";"";"16/03/2005";"G";01/09/2020;;"";"ANGLAIS LV1";"ESPAGNOL LV2";"ACCOMPAGNEMT. PERSO.";"ACCOMP.CHOIX ORIENT."
"ARNI Léo";"";"02/10/1983";"G";01/09/2020;;"";"ANGLAIS LV1";"ESPAGNOL LV2";"ACCOMPAGNEMT. PERSO.";"ACCOMP.CHOIX ORIENT."
"BAUDON Samuel Quentin Jaques";"";"14/10/2005";"G";01/09/2020;;"";"ANGLAIS LV1";"ESPAGNOL LV2";"ACCOMPAGNEMT. PERSO.";"ACCOMP.CHOIX ORIENT."
"LE PAIN--PERDU Alexia";"";"11/07/2005";"F";01/09/2020;;"";"ANGLAIS LV1";"ESPAGNOL LV2";"ACCOMPAGNEMT. PERSO.";"ACCOMP.CHOIX ORIENT."
"LE BEURRE Jeanne";"";"02/04/2005";"F";01/09/2020;;"";"ANGLAIS LV1";"ESPAGNOL LV2";"ACCOMPAGNEMT. PERSO.";"ACCOMP.CHOIX ORIENT."
"TOURS Mathias";"";"29/03/2005";"G";01/09/2020;;"";"ANGLAIS LV1";"ESPAGNOL LV2";"ACCOMPAGNEMT. PERSO.";"ACCOMP.CHOIX ORIENT."
```
Ca fonctionne:
![image](https://user-images.githubusercontent.com/44053087/92914923-5e890d80-f42c-11ea-8fe4-c57d5bf1e7a7.png)

Reste à [documenter l'outil](https://github.com/cspaier/pronote2wims/issues/6).

**Comment by Badatos** [comment]
Je viens de tester également (merci pour le jeu d'essai :), et en effet cela fonctionne.

Ceci dit : le message "Trop court" ne s'affiche que lorsque l'on passe la souris sur le mot de passe en rouge.
On ne se rend pas immédiatement compte du problème. D'ailleurs si on a beaucoup d'élèves et que les premiers ne posent pas de souci, on peut très facilement passer à côté d'un texte en rouge si on ne descend pas l'assenceur jusqu'en bas.

Que diriez-vous d'ajouter un message général avant le tableau récapitulatif, qui serait soit :
- (en vert) Conversion effectuée avec succès.
- (en rouge) Des erreurs sont survenues pendant la conversion, merci de consulter le tableau récapitulatif ci-dessous
?

**Comment by cspaier** [comment]
Merci du retour.

> Ceci dit : le message "Trop court" ne s'affiche que lorsque l'on passe la souris sur le mot de passe en rouge.

C'est voulu. Une ligne peut contenir plusieurs erreurs et survoller l'erreur permet d'avoir des détails.

> Que diriez-vous d'ajouter un message général avant le tableau récapitulatif, qui serait soit :

    (en vert) Conversion effectuée avec succès.
    (en rouge) Des erreurs sont survenues pendant la conversion, merci de consulter le tableau récapitulatif ci-dessous
    ?

Bonne idée.
De manière générale, cet outil a été créé dans un premier temps pour une utilisation quasi personelle et manque cruellement de documentation.
