### ISSUE TITLE
Accents non reconnus

### ISSUE THREAD

**Issue by Badatos** [cspaier/pronote2wims#9]
Bonjour,
Il semble que lorsque la liste d'utilisateurs de Pronote contient des accents, ceux-ci ne soient pas toujours encodés convenablement pour WIMS et cela crée des caractères bizarres, comme "MÃ©lissa" par exemple.

Dans les classes WIMS en français, l'encodage utilisé est "Windows-1252" (chaque langue a son encodage). Pour corriger ce souci, je vous propose par exemple de remplacer l'usage de la librairie "StringIO" par ceci : 

```
f = open('out.csv', 'w', encoding='Windows-1252', newline='')
w = csv.DictWriter(f,fieldnames=fieldnames)
```

**Comment by cspaier** [comment]
Re-bonjour,

Merci pour ce retour et cette proposition de correction.

Si vous avez testé ce code, je ne vois pas d'inconvénient à l'utiliser.

J'attends votre pull request?

**Comment by Badatos** [comment]
Désolé, je n'ai ni pronote, ni de serveur pronote2wims, je n'ai donc pas testé la piste suggérée.

**Comment by cspaier** [comment]
> ni de serveur pronote2wims

Le readme contient des instructions permettant de deployer le serveur simplement.

Il serait bon d'avoir des CSV de test par contre.

Comment avez-vous constaté ce problème?

Je teste cela quand je peux.

**Comment by cspaier** [comment]
Je n'arrive pas à reproduire le problème et attends donc un fichier CSV pour reproduire et tester.

**Comment by Badatos** [comment]
Bonjour Clément,
En fait j'ai testé avec le CSV de test que tu as envoyé dans l'autre Issue, et le souci s'est bien produit (accents dans les noms ne s'affichent pas correctement une fois importés dans WIMS)

```
Élève;;Né(e) le;Sexe;Entrée;Sortie;Classe de rattachement;Option 1;Option 2;Option 3;Autres options
"ALADIN Marthe";"";"19/01/2005";"F";01/09/2020;;"";"ANGLAIS LV1";"ESPAGNOL LV2";"ACCOMPAGNEMT. PERSO.";"ACCOMP.CHOIX ORIENT."
"ALLUMINIUM Paul";"";"16/03/2005";"G";01/09/2020;;"";"ANGLAIS LV1";"ESPAGNOL LV2";"ACCOMPAGNEMT. PERSO.";"ACCOMP.CHOIX ORIENT."
"ARNI Léo";"";"02/10/1983";"G";01/09/2020;;"";"ANGLAIS LV1";"ESPAGNOL LV2";"ACCOMPAGNEMT. PERSO.";"ACCOMP.CHOIX ORIENT."
"BAUDON Samuel Quentin Jaques";"";"14/10/2005";"G";01/09/2020;;"";"ANGLAIS LV1";"ESPAGNOL LV2";"ACCOMPAGNEMT. PERSO.";"ACCOMP.CHOIX ORIENT."
"LE PAIN--PERDU Alexia";"";"11/07/2005";"F";01/09/2020;;"";"ANGLAIS LV1";"ESPAGNOL LV2";"ACCOMPAGNEMT. PERSO.";"ACCOMP.CHOIX ORIENT."
"LE BEURRE Jeanne";"";"02/04/2005";"F";01/09/2020;;"";"ANGLAIS LV1";"ESPAGNOL LV2";"ACCOMPAGNEMT. PERSO.";"ACCOMP.CHOIX ORIENT."
"TOURS Mathias";"";"29/03/2005";"G";01/09/2020;;"";"ANGLAIS LV1";"ESPAGNOL LV2";"ACCOMPAGNEMT. PERSO.";"ACCOMP.CHOIX ORIENT."
```

ARNI Léo par exemple s'affiche ARNI LÃ©o

**Comment by cspaier** [comment]
Bonjour,

Merci pour le test et le retour.

Je vais essayer ta proposition cette semaine.

Par contre j'avais cru comprendre que `open` prenait en entrée un nom de fichier qu'il ouvrait effectivement alors que `stringIO` permet de créer un fichier en mémoire. Je me penche la dessus.

> Dans les classes WIMS en français, l'encodage utilisé est "Windows-1252"
Une raison pour ne pas utiliser uft8 chez wims?

**Comment by Badatos** [comment]
De rien ;)

> Par contre j'avais cru comprendre que `open` prenait en entrée un nom de fichier qu'il ouvrait effectivement alors que `stringIO` permet de créer un fichier en mémoire. Je me penche la dessus.

Oui c'est possible. J'avoue que je ne connais pas assez les 2, et le peu que j'ai utilisé python était avec des fichiers réels en effet.
 
> > Dans les classes WIMS en français, l'encodage utilisé est "Windows-1252"

> Une raison pour ne pas utiliser uft8 chez wims?

En fait, WIMS existe depuis plus longtemps que UTF-8, qui n'a vu son usage s'étendre réellement qu'à partir de 2006 (voir ici https://fr.wikipedia.org/wiki/UTF-8#Évolution_des_usages )

Il faudra en effet tôt ou tard passer à l'UTF-8, mais c'est un très gros travail, ne serait-ce que de convertir l'ensemble des modules. Et avant cela, il y a un travail préliminaire à faire dans le code C de WIMS pour s'assurer que toutes les fonctions de manipulation de chaines propres à WIMS fonctionnent toujours avec un encodage dont la taille de chaque caractère est variable (alors que pour l'instant il utilise des encodages à taille fixe).

**Comment by byache** [comment]
Bonjour Olivier,
Je viens de tester en inscrivant mes élèves et je n'ai rencontré aucune erreur.
Par contre, en copiant-collant le csv de test dans libreoffice et en uploadant ce résultat, j'ai eu des trucs incorrects. Donc cet outil n'est peut-être pas super robuste en ce qui concerne la façon dont les champs du csv sont reconnus.
Par contre, si on se contente du fichier généré par pronote (quitte à le modifier en l'éditant), aucun problème de mon côté.
D'après le forum wimsedu, la personne qui a signalé le pb a peut-être mal compris d'où il venait.

**Comment by cspaier** [comment]
Salut Paul!
Merci pour le test.

> Donc cet outil n'est peut-être pas super robuste en ce qui concerne la façon dont les champs du csv sont reconnus.

Je crois que c'est juste un problème d'encodage. On sort un csv en utf8 et wims mange du vieux  "Windows-1252". Il suffit de forcer l'encodage du csv. Faut que je regarde comment faire ca. Au pire du pire on sera forcé de faire un fichier avec `open`.

@Badatos : Merci pour les éclaircissement coté wims.

**Comment by cspaier** [comment]
Une [piste](https://github.com/pallets/flask/issues/1005#issuecomment-50972286).

**Comment by byache** [comment]
Je confirme avoir rencontré le problème : j'ai inscrit une classe où un prénom comporte un "é" et un autre un "ï".
Le "é" n'a pas été reconnu et j'ai dû le modifier manuellement dans wims une l'inscription faite.

**Comment by cspaier** [comment]
J'ai testé un peu et ca fonctionne. N'hésitez pas envoyer d'autres retours de tests.
